# Generated by Django 4.1.5 on 2023-01-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50)),
                ('name2', models.CharField(max_length=50)),
                ('name3', models.CharField(max_length=50)),
                ('name4', models.CharField(max_length=50)),
                ('roll1', models.IntegerField()),
                ('roll2', models.IntegerField()),
                ('roll3', models.IntegerField()),
                ('roll4', models.IntegerField()),
                ('email1', models.EmailField(max_length=200)),
                ('email2', models.EmailField(max_length=200)),
                ('email3', models.EmailField(max_length=200)),
                ('email4', models.EmailField(max_length=200)),
                ('phone1', models.IntegerField()),
                ('phone2', models.IntegerField()),
                ('phone3', models.IntegerField()),
                ('phone4', models.IntegerField()),
            ],
        ),
    ]
